import type {
  Brand,
  Category,
  LocalizedText,
  Product,
  ProductImage,
  ProductSpecification,
  Promotion,
  PromotionType,
} from "@/types/domain";
import { toMinor } from "@/utils/money";

const createdAt = "2026-07-01T09:00:00.000Z";
const updatedAt = "2026-08-10T12:00:00.000Z";
const future = "2027-12-31T23:59:59.000Z";

const l = (ru: string, kg: string, en: string): LocalizedText => ({ ru, kg, en });

export const mockCategories: Category[] = [
  ["cat-kitchen", "kitchen", l("Для кухни", "Ашкана үчүн", "Kitchen"), "ChefHat"],
  ["cat-cleaning", "cleaning", l("Уборка", "Тазалоо", "Cleaning"), "Sparkles"],
  ["cat-climate", "climate", l("Климат", "Климат", "Climate"), "AirVent"],
  ["cat-large", "large", l("Крупная техника", "Ири техника", "Major appliances"), "Refrigerator"],
  ["cat-entertainment", "entertainment", l("ТВ и развлечения", "ТВ жана көңүл ачуу", "TV & entertainment"), "Tv"],
  ["cat-care", "care", l("Уход за собой", "Жеке кам көрүү", "Personal care"), "HeartPulse"],
].map(([id, slug, name, icon]) => ({
  id: id as string,
  slug: slug as string,
  name: name as LocalizedText,
  icon: icon as string,
  isVisible: true,
  createdAt,
  updatedAt,
}));

export const mockBrands: Brand[] = ["Samsung", "LG", "Bosch", "Xiaomi", "Haier", "Philips", "Tefal", "Artel", "Beko", "Dyson"].map(
  (name, index) => ({
    id: `brand-${index + 1}`,
    name,
    slug: name.toLowerCase(),
    createdAt,
    updatedAt,
  }),
);

const image = (id: string, url: string, name: LocalizedText, position = 0): ProductImage => ({
  id,
  url,
  alt: name,
  position,
});

const spec = (id: string, label: LocalizedText, value: LocalizedText): ProductSpecification => ({
  id,
  label,
  value,
});

const promo = (
  id: string,
  type: PromotionType,
  title: LocalizedText,
  discountPercent?: number,
  cashbackPercent?: number,
  specialPrice?: number,
): Promotion => ({
  id,
  type,
  title,
  startAt: "2026-08-01T00:00:00.000Z",
  endAt: future,
  discountPercent,
  cashbackPercent,
  specialPrice: specialPrice ? toMinor(specialPrice) : undefined,
  isActive: true,
  createdAt,
  updatedAt,
});

const productImageUrls = {
  fridge: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=900&q=84",
  washer: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=900&q=84",
  vacuum: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=900&q=84",
  microwave: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=900&q=84",
  coffee: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=900&q=84",
  kitchen: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=84",
  tv: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=84",
  climate: "https://images.unsplash.com/photo-1631545806609-1c798586cfaf?auto=format&fit=crop&w=900&q=84",
  iron: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=900&q=84",
  care: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=900&q=84",
};

interface SeedProduct {
  id: string;
  sku: string;
  slug: string;
  name: LocalizedText;
  brand: string;
  model: string;
  categoryId: string;
  supplierId: string;
  price: number;
  oldPrice?: number;
  purchase: number;
  stock: number;
  rating: number;
  views: number;
  image: string;
  promotion?: Promotion;
  featured?: boolean;
  popular?: boolean;
  installment?: boolean;
}

const seeds: SeedProduct[] = [
  {
    id: "product-1",
    sku: "TC2-1001",
    slug: "samsung-rb33",
    name: l("Холодильник Samsung No Frost", "Samsung No Frost муздаткычы", "Samsung No Frost refrigerator"),
    brand: "Samsung",
    model: "RB33A32N0SA",
    categoryId: "cat-large",
    supplierId: "supplier-1",
    price: 56990,
    oldPrice: 63990,
    purchase: 47800,
    stock: 7,
    rating: 4.9,
    views: 1320,
    image: productImageUrls.fridge,
    promotion: promo("promo-1", "discount", l("Скидка", "Арзандатуу", "Discount"), 11),
    featured: true,
    popular: true,
  },
  {
    id: "product-2",
    sku: "TC2-1002",
    slug: "lg-washer-f2v5",
    name: l("Стиральная машина LG 8 кг", "LG 8 кг кир жуугуч машинасы", "LG 8 kg washing machine"),
    brand: "LG",
    model: "F2V5HS0W",
    categoryId: "cat-large",
    supplierId: "supplier-1",
    price: 48990,
    oldPrice: 52990,
    purchase: 41200,
    stock: 5,
    rating: 4.8,
    views: 1180,
    image: productImageUrls.washer,
    promotion: promo("promo-2", "sale", l("Акция недели", "Аптанын акциясы", "Deal of the week"), 8),
    featured: true,
    popular: true,
  },
  {
    id: "product-3",
    sku: "TC2-1003",
    slug: "xiaomi-vacuum-s10",
    name: l("Робот-пылесос Xiaomi S10", "Xiaomi S10 робот чаң соргучу", "Xiaomi S10 robot vacuum"),
    brand: "Xiaomi",
    model: "S10 EU",
    categoryId: "cat-cleaning",
    supplierId: "supplier-2",
    price: 28990,
    oldPrice: 31990,
    purchase: 23500,
    stock: 11,
    rating: 4.7,
    views: 1640,
    image: productImageUrls.vacuum,
    promotion: promo("promo-3", "cashback", l("Кешбэк 5%", "5% кешбэк", "5% cashback"), undefined, 5),
    featured: true,
    popular: true,
  },
  {
    id: "product-4",
    sku: "TC2-1004",
    slug: "bosch-microwave-bfl",
    name: l("Микроволновая печь Bosch", "Bosch микротолкундуу меши", "Bosch microwave oven"),
    brand: "Bosch",
    model: "BFL524MS0",
    categoryId: "cat-kitchen",
    supplierId: "supplier-2",
    price: 23990,
    oldPrice: 26990,
    purchase: 19800,
    stock: 4,
    rating: 4.8,
    views: 890,
    image: productImageUrls.microwave,
    promotion: promo("promo-4", "giveaway", l("Участвует в розыгрыше", "Утушка катышат", "Giveaway entry")),
    featured: true,
  },
  {
    id: "product-5",
    sku: "TC2-1005",
    slug: "philips-coffee-5400",
    name: l("Кофемашина Philips LatteGo", "Philips LatteGo кофе машинасы", "Philips LatteGo coffee machine"),
    brand: "Philips",
    model: "EP5447/90",
    categoryId: "cat-kitchen",
    supplierId: "supplier-3",
    price: 79990,
    oldPrice: 87990,
    purchase: 68100,
    stock: 2,
    rating: 4.9,
    views: 720,
    image: productImageUrls.coffee,
    promotion: promo("promo-5", "hit", l("Хит продаж", "Көп сатылган", "Bestseller")),
    featured: true,
    popular: true,
  },
  {
    id: "product-6",
    sku: "TC2-1006",
    slug: "tefal-blender-bl87",
    name: l("Блендер Tefal PerfectMix+", "Tefal PerfectMix+ блендери", "Tefal PerfectMix+ blender"),
    brand: "Tefal",
    model: "BL87G831",
    categoryId: "cat-kitchen",
    supplierId: "supplier-3",
    price: 12990,
    oldPrice: 14990,
    purchase: 9400,
    stock: 18,
    rating: 4.7,
    views: 610,
    image: productImageUrls.kitchen,
    promotion: promo("promo-6", "new", l("Новинка", "Жаңы", "New")),
    featured: true,
  },
  {
    id: "product-7",
    sku: "TC2-1007",
    slug: "haier-ac-flexis",
    name: l("Кондиционер Haier Flexis", "Haier Flexis кондиционери", "Haier Flexis air conditioner"),
    brand: "Haier",
    model: "AS35S2SF1FA",
    categoryId: "cat-climate",
    supplierId: "supplier-1",
    price: 52990,
    oldPrice: 58990,
    purchase: 43600,
    stock: 6,
    rating: 4.8,
    views: 1420,
    image: productImageUrls.climate,
    promotion: promo("promo-7", "sale", l("Летняя акция", "Жайкы акция", "Summer deal"), 10),
    featured: true,
    popular: true,
  },
  {
    id: "product-8",
    sku: "TC2-1008",
    slug: "samsung-qled-55",
    name: l("Телевизор Samsung QLED 55\"", "Samsung QLED 55\" сыналгысы", "Samsung QLED 55\" TV"),
    brand: "Samsung",
    model: "QE55Q60C",
    categoryId: "cat-entertainment",
    supplierId: "supplier-2",
    price: 64990,
    oldPrice: 71990,
    purchase: 54700,
    stock: 8,
    rating: 4.9,
    views: 1760,
    image: productImageUrls.tv,
    promotion: promo("promo-8", "cashback", l("Кешбэк 7%", "7% кешбэк", "7% cashback"), undefined, 7),
    featured: true,
    popular: true,
  },
  {
    id: "product-9",
    sku: "TC2-1009",
    slug: "dyson-v12",
    name: l("Вертикальный пылесос Dyson V12", "Dyson V12 тик чаң соргучу", "Dyson V12 cordless vacuum"),
    brand: "Dyson",
    model: "V12 Detect Slim",
    categoryId: "cat-cleaning",
    supplierId: "supplier-3",
    price: 68990,
    oldPrice: 74990,
    purchase: 59200,
    stock: 3,
    rating: 4.9,
    views: 1510,
    image: productImageUrls.vacuum,
    promotion: promo("promo-9", "hit", l("Хит", "Хит", "Hot")),
    featured: true,
    popular: true,
  },
  {
    id: "product-10",
    sku: "TC2-1010",
    slug: "beko-dishwasher",
    name: l("Посудомоечная машина Beko", "Beko идиш жуугуч машинасы", "Beko dishwasher"),
    brand: "Beko",
    model: "DFN28422W",
    categoryId: "cat-large",
    supplierId: "supplier-1",
    price: 39990,
    purchase: 33400,
    stock: 0,
    rating: 4.6,
    views: 540,
    image: productImageUrls.washer,
  },
  {
    id: "product-11",
    sku: "TC2-1011",
    slug: "artel-oven",
    name: l("Мини-печь Artel 45 л", "Artel 45 л мини меши", "Artel 45 L mini oven"),
    brand: "Artel",
    model: "MD-4518",
    categoryId: "cat-kitchen",
    supplierId: "supplier-2",
    price: 11990,
    oldPrice: 13490,
    purchase: 8900,
    stock: 14,
    rating: 4.5,
    views: 430,
    image: productImageUrls.microwave,
    promotion: promo("promo-11", "discount", l("Скидка", "Арзандатуу", "Discount"), 11),
  },
  {
    id: "product-12",
    sku: "TC2-1012",
    slug: "philips-iron",
    name: l("Утюг Philips Azur", "Philips Azur үтүгү", "Philips Azur iron"),
    brand: "Philips",
    model: "DST7040/80",
    categoryId: "cat-care",
    supplierId: "supplier-3",
    price: 7990,
    purchase: 5800,
    stock: 25,
    rating: 4.7,
    views: 390,
    image: productImageUrls.iron,
    promotion: promo("promo-12", "new", l("Новинка", "Жаңы", "New")),
  },
  {
    id: "product-13",
    sku: "TC2-1013",
    slug: "xiaomi-tv-43",
    name: l("Телевизор Xiaomi TV A 43\"", "Xiaomi TV A 43\" сыналгысы", "Xiaomi TV A 43\""),
    brand: "Xiaomi",
    model: "L43M8-A2RU",
    categoryId: "cat-entertainment",
    supplierId: "supplier-2",
    price: 31990,
    oldPrice: 34990,
    purchase: 26700,
    stock: 9,
    rating: 4.6,
    views: 1100,
    image: productImageUrls.tv,
    promotion: promo("promo-13", "sale", l("Выгодная цена", "Пайдалуу баа", "Special price"), 9),
    popular: true,
  },
  {
    id: "product-14",
    sku: "TC2-1014",
    slug: "haier-freezer",
    name: l("Морозильная камера Haier", "Haier тоңдургуч камерасы", "Haier freezer"),
    brand: "Haier",
    model: "HF-260",
    categoryId: "cat-large",
    supplierId: "supplier-1",
    price: 45990,
    purchase: 38800,
    stock: 4,
    rating: 4.6,
    views: 620,
    image: productImageUrls.fridge,
  },
  {
    id: "product-15",
    sku: "TC2-1015",
    slug: "bosch-food-processor",
    name: l("Кухонный комбайн Bosch", "Bosch ашкана комбайны", "Bosch food processor"),
    brand: "Bosch",
    model: "MUMS2VM00",
    categoryId: "cat-kitchen",
    supplierId: "supplier-2",
    price: 19990,
    purchase: 16100,
    stock: 12,
    rating: 4.7,
    views: 470,
    image: productImageUrls.kitchen,
    promotion: promo("promo-15", "giveaway", l("Розыгрыш", "Утуш", "Giveaway")),
  },
  {
    id: "product-16",
    sku: "TC2-1016",
    slug: "lg-air-purifier",
    name: l("Очиститель воздуха LG PuriCare", "LG PuriCare аба тазалагычы", "LG PuriCare air purifier"),
    brand: "LG",
    model: "AS60GDWV0",
    categoryId: "cat-climate",
    supplierId: "supplier-1",
    price: 42990,
    purchase: 35900,
    stock: 5,
    rating: 4.8,
    views: 680,
    image: productImageUrls.climate,
    promotion: promo("promo-16", "cashback", l("Кешбэк 4%", "4% кешбэк", "4% cashback"), undefined, 4),
  },
  {
    id: "product-17",
    sku: "TC2-1017",
    slug: "tefal-kettle",
    name: l("Электрочайник Tefal 1,7 л", "Tefal 1,7 л электр чайнеги", "Tefal 1.7 L electric kettle"),
    brand: "Tefal",
    model: "KO260130",
    categoryId: "cat-kitchen",
    supplierId: "supplier-3",
    price: 4990,
    oldPrice: 5790,
    purchase: 3400,
    stock: 31,
    rating: 4.6,
    views: 580,
    image: productImageUrls.kitchen,
    promotion: promo("promo-17", "discount", l("Скидка", "Арзандатуу", "Discount"), 14),
  },
  {
    id: "product-18",
    sku: "TC2-1018",
    slug: "philips-hairdryer",
    name: l("Фен Philips ThermoProtect", "Philips ThermoProtect чач кургаткычы", "Philips ThermoProtect hair dryer"),
    brand: "Philips",
    model: "BHD350/10",
    categoryId: "cat-care",
    supplierId: "supplier-3",
    price: 4590,
    purchase: 3100,
    stock: 22,
    rating: 4.5,
    views: 350,
    image: productImageUrls.care,
  },
];

export const mockProducts: Product[] = seeds.map((seed) => {
  const description = l(
    `${seed.name.ru} — проверенная техника для дома с официальной гарантией и доставкой по Кыргызстану.`,
    `${seed.name.kg} — кепилдик жана Кыргызстан боюнча жеткирүү менен ишенимдүү техника.`,
    `${seed.name.en} — reliable home appliance with warranty and delivery across Kyrgyzstan.`,
  );
  const specifications = [
    spec(`${seed.id}-spec-1`, l("Гарантия", "Кепилдик", "Warranty"), l("12 месяцев", "12 ай", "12 months")),
    spec(`${seed.id}-spec-2`, l("Страна бренда", "Бренд өлкөсү", "Brand origin"), l("Международный бренд", "Эл аралык бренд", "International brand")),
    spec(`${seed.id}-spec-3`, l("Состояние", "Абалы", "Condition"), l("Новый", "Жаңы", "New")),
  ];
  const gallery = [
    image(`${seed.id}-img-1`, seed.image, seed.name, 0),
    image(`${seed.id}-img-2`, `${seed.image}&sat=-8`, seed.name, 1),
    image(`${seed.id}-img-3`, `${seed.image}&crop=entropy`, seed.name, 2),
  ];
  return {
    id: seed.id,
    sku: seed.sku,
    slug: seed.slug,
    name: seed.name,
    brand: seed.brand,
    model: seed.model,
    categoryId: seed.categoryId,
    supplierId: seed.supplierId,
    description,
    specifications,
    purchasePrice: toMinor(seed.purchase),
    salePrice: toMinor(seed.price),
    oldPrice: seed.oldPrice ? toMinor(seed.oldPrice) : undefined,
    stock: seed.stock,
    reserved: seed.stock > 0 ? Math.min(seed.stock, seed.id === "product-5" ? 1 : 0) : 0,
    minimumStock: 4,
    warrantyMonths: 12,
    managerRewardType: "percent",
    managerRewardValue: 500,
    images: gallery,
    promotion: seed.promotion,
    isFeatured: seed.featured ?? false,
    isPopular: seed.popular ?? false,
    isVisible: true,
    isArchived: false,
    installmentEligible: seed.installment ?? true,
    rating: seed.rating,
    views: seed.views,
    source: "supplier",
    arrivalDate: createdAt,
    createdAt,
    updatedAt,
  };
});
