-- Supplier delivery -> product -> inventory -> finance flow.
-- Also makes installment totals and schedules use the same configured rates
-- as the storefront calculator.

create table if not exists public.supplier_deliveries (
  id uuid primary key default gen_random_uuid(),
  delivery_number bigint generated by default as identity unique,
  supplier_id uuid not null references public.suppliers(id) on delete restrict,
  delivered_at date not null default current_date,
  total_quantity integer not null check (total_quantity > 0),
  notes text,
  status text not null default 'received'
    check (status in ('received','cancelled')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplier_delivery_items (
  id uuid primary key default gen_random_uuid(),
  delivery_id uuid not null references public.supplier_deliveries(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null check (length(trim(product_name)) between 2 and 160),
  brand text not null check (length(trim(brand)) between 1 and 100),
  model text not null check (length(trim(model)) between 1 and 120),
  supplier_sku text,
  quantity integer not null check (quantity > 0),
  purchase_price_tyiyn bigint not null check (purchase_price_tyiyn > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (delivery_id, model, supplier_sku)
);

create index if not exists supplier_deliveries_supplier_id_idx
  on public.supplier_deliveries(supplier_id, delivered_at desc);
create index if not exists supplier_deliveries_created_by_idx
  on public.supplier_deliveries(created_by);
create index if not exists supplier_delivery_items_delivery_id_idx
  on public.supplier_delivery_items(delivery_id);
create index if not exists supplier_delivery_items_product_id_idx
  on public.supplier_delivery_items(product_id);

alter table public.products
  add column if not exists deleted_at timestamptz;

alter table public.supplier_products
  add column if not exists delivery_item_id uuid
    references public.supplier_delivery_items(id) on delete set null;
create unique index if not exists supplier_products_delivery_item_id_uidx
  on public.supplier_products(delivery_item_id)
  where delivery_item_id is not null;

alter table public.supplier_deliveries enable row level security;
alter table public.supplier_delivery_items enable row level security;

drop policy if exists supplier_deliveries_admin_all on public.supplier_deliveries;
create policy supplier_deliveries_admin_all
on public.supplier_deliveries for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists supplier_delivery_items_admin_all on public.supplier_delivery_items;
create policy supplier_delivery_items_admin_all
on public.supplier_delivery_items for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update, delete on public.supplier_deliveries to authenticated;
grant select, insert, update, delete on public.supplier_delivery_items to authenticated;

create or replace function public.create_supplier_with_delivery(
  p_supplier jsonb,
  p_items jsonb,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_supplier_id uuid;
  v_delivery_id uuid;
  v_delivery_number bigint;
  v_item jsonb;
  v_quantity integer;
  v_purchase_price bigint;
  v_total_quantity integer := 0;
  v_name text;
begin
  if not public.is_admin() then raise exception 'Только управляющий может оформлять поставки'; end if;
  if jsonb_typeof(p_supplier) <> 'object' then raise exception 'Укажите поставщика'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Добавьте хотя бы одну модель поставки';
  end if;
  if jsonb_array_length(p_items) > 50 then raise exception 'В одной поставке допустимо не более 50 моделей'; end if;

  v_name := trim(coalesce(p_supplier ->> 'name',''));
  if length(v_name) < 2 then raise exception 'Укажите название поставщика'; end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_quantity := (v_item ->> 'quantity')::integer;
      v_purchase_price := (v_item ->> 'purchase_price_tyiyn')::bigint;
    exception when others then
      raise exception 'Проверьте количество и закупочную цену каждой модели';
    end;
    if length(trim(coalesce(v_item ->> 'product_name',''))) < 2
       or length(trim(coalesce(v_item ->> 'brand',''))) < 1
       or length(trim(coalesce(v_item ->> 'model',''))) < 1 then
      raise exception 'Укажите товар, бренд и модель в каждой строке';
    end if;
    if v_quantity <= 0 or v_quantity > 100000 then raise exception 'Количество каждой модели должно быть больше нуля'; end if;
    if v_purchase_price <= 0 then raise exception 'Закупочная цена должна быть больше нуля'; end if;
    v_total_quantity := v_total_quantity + v_quantity;
  end loop;

  insert into public.suppliers (
    name, contact_person, phone, whatsapp, email, address, notes, created_by
  ) values (
    v_name,
    nullif(trim(p_supplier ->> 'contact_person'),''),
    nullif(trim(p_supplier ->> 'phone'),''),
    nullif(trim(p_supplier ->> 'whatsapp'),''),
    nullif(trim(p_supplier ->> 'email'),''),
    nullif(trim(p_supplier ->> 'address'),''),
    nullif(trim(p_supplier ->> 'notes'),''),
    auth.uid()
  ) returning id into v_supplier_id;

  insert into public.supplier_deliveries (
    supplier_id, total_quantity, notes, created_by
  ) values (
    v_supplier_id, v_total_quantity, nullif(trim(p_notes),''), auth.uid()
  ) returning id, delivery_number into v_delivery_id, v_delivery_number;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    insert into public.supplier_delivery_items (
      delivery_id, product_name, brand, model, supplier_sku,
      quantity, purchase_price_tyiyn
    ) values (
      v_delivery_id,
      trim(v_item ->> 'product_name'),
      trim(v_item ->> 'brand'),
      trim(v_item ->> 'model'),
      nullif(trim(v_item ->> 'supplier_sku'),''),
      (v_item ->> 'quantity')::integer,
      (v_item ->> 'purchase_price_tyiyn')::bigint
    );
  end loop;

  return jsonb_build_object(
    'supplier_id', v_supplier_id,
    'delivery_id', v_delivery_id,
    'delivery_number', v_delivery_number,
    'total_quantity', v_total_quantity
  );
end;
$$;

create or replace function public.create_supplier_delivery(
  p_supplier_id uuid,
  p_items jsonb,
  p_notes text default null,
  p_delivered_at date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_delivery_id uuid;
  v_delivery_number bigint;
  v_item jsonb;
  v_quantity integer;
  v_purchase_price bigint;
  v_total_quantity integer := 0;
begin
  if not public.is_admin() then raise exception 'Только управляющий может оформлять поставки'; end if;
  if not exists (select 1 from public.suppliers where id = p_supplier_id and is_active) then
    raise exception 'Поставщик не найден или архивирован';
  end if;
  if p_delivered_at > current_date then raise exception 'Дата поставки не может быть в будущем'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Добавьте хотя бы одну модель поставки';
  end if;
  if jsonb_array_length(p_items) > 50 then raise exception 'В одной поставке допустимо не более 50 моделей'; end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_quantity := (v_item ->> 'quantity')::integer;
      v_purchase_price := (v_item ->> 'purchase_price_tyiyn')::bigint;
    exception when others then
      raise exception 'Проверьте количество и закупочную цену каждой модели';
    end;
    if length(trim(coalesce(v_item ->> 'product_name',''))) < 2
       or length(trim(coalesce(v_item ->> 'brand',''))) < 1
       or length(trim(coalesce(v_item ->> 'model',''))) < 1 then
      raise exception 'Укажите товар, бренд и модель в каждой строке';
    end if;
    if v_quantity <= 0 or v_quantity > 100000 then raise exception 'Количество каждой модели должно быть больше нуля'; end if;
    if v_purchase_price <= 0 then raise exception 'Закупочная цена должна быть больше нуля'; end if;
    v_total_quantity := v_total_quantity + v_quantity;
  end loop;

  insert into public.supplier_deliveries (
    supplier_id, delivered_at, total_quantity, notes, created_by
  ) values (
    p_supplier_id, coalesce(p_delivered_at,current_date), v_total_quantity,
    nullif(trim(p_notes),''), auth.uid()
  ) returning id, delivery_number into v_delivery_id, v_delivery_number;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    insert into public.supplier_delivery_items (
      delivery_id, product_name, brand, model, supplier_sku,
      quantity, purchase_price_tyiyn
    ) values (
      v_delivery_id,
      trim(v_item ->> 'product_name'),
      trim(v_item ->> 'brand'),
      trim(v_item ->> 'model'),
      nullif(trim(v_item ->> 'supplier_sku'),''),
      (v_item ->> 'quantity')::integer,
      (v_item ->> 'purchase_price_tyiyn')::bigint
    );
  end loop;

  return jsonb_build_object(
    'supplier_id', p_supplier_id,
    'delivery_id', v_delivery_id,
    'delivery_number', v_delivery_number,
    'total_quantity', v_total_quantity
  );
end;
$$;

create or replace function public.create_product_from_delivery_item(
  p_delivery_item_id uuid,
  p_product jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.supplier_delivery_items%rowtype;
  v_delivery public.supplier_deliveries%rowtype;
  v_brand_id uuid;
  v_product_id uuid;
  v_category_id uuid;
  v_sale_price bigint;
  v_old_price bigint;
  v_minimum_stock integer;
  v_warranty integer;
  v_commission_type text;
  v_commission_value bigint;
  v_sku text;
  v_slug text;
begin
  if not public.is_admin() then raise exception 'Только управляющий может добавлять товары'; end if;
  if jsonb_typeof(p_product) <> 'object' then raise exception 'Некорректные данные товара'; end if;

  select * into v_item from public.supplier_delivery_items
  where id = p_delivery_item_id for update;
  if not found then raise exception 'Строка поставки не найдена'; end if;
  if v_item.product_id is not null then raise exception 'Для этой модели товар уже создан'; end if;

  select * into v_delivery from public.supplier_deliveries
  where id = v_item.delivery_id and status = 'received' for update;
  if not found then raise exception 'Поставка недоступна'; end if;

  begin
    v_category_id := (p_product ->> 'category_id')::uuid;
    v_sale_price := (p_product ->> 'sale_price_tyiyn')::bigint;
    v_old_price := nullif(p_product ->> 'old_price_tyiyn','')::bigint;
    v_minimum_stock := coalesce((p_product ->> 'minimum_stock')::integer,0);
    v_warranty := coalesce((p_product ->> 'warranty_months')::integer,0);
    v_commission_value := (p_product ->> 'manager_commission_value')::bigint;
  exception when others then
    raise exception 'Проверьте категорию, цену, остаток, гарантию и комиссию';
  end;

  v_commission_type := coalesce(p_product ->> 'manager_commission_type','percent');
  v_sku := trim(coalesce(p_product ->> 'sku',''));
  v_slug := trim(coalesce(p_product ->> 'slug',''));

  if not exists (select 1 from public.categories where id = v_category_id and is_active) then
    raise exception 'Выберите действующую категорию';
  end if;
  if length(trim(coalesce(p_product ->> 'name_ru',''))) < 2 then raise exception 'Укажите название товара'; end if;
  if length(v_sku) < 2 or length(v_slug) < 2 then raise exception 'Укажите SKU и адрес товара'; end if;
  if v_sale_price <= 0 then raise exception 'Цена продажи должна быть больше нуля'; end if;
  if v_old_price is not null and v_old_price < v_sale_price then raise exception 'Старая цена не может быть ниже цены продажи'; end if;
  if v_minimum_stock < 0 or v_warranty < 0 then raise exception 'Остаток и гарантия не могут быть отрицательными'; end if;
  if v_commission_type not in ('percent','fixed') then raise exception 'Некорректный тип комиссии'; end if;
  if v_commission_value < 0 then raise exception 'Комиссия не может быть отрицательной'; end if;
  if v_commission_type = 'percent' and v_commission_value > 10000 then
    raise exception 'Процент менеджера не может превышать 100%%';
  end if;

  select id into v_brand_id from public.brands
  where lower(name) = lower(v_item.brand)
  order by created_at limit 1;
  if v_brand_id is null then
    insert into public.brands(name, slug)
    values (
      v_item.brand,
      left(regexp_replace(lower(v_item.brand), '[^a-z0-9а-яё]+', '-', 'gi'), 80)
        || '-' || substr(replace(gen_random_uuid()::text,'-',''),1,8)
    ) returning id into v_brand_id;
  end if;

  insert into public.products (
    category_id, brand_id, sku, slug, model,
    name_ru, name_kg, name_en,
    description_ru, description_kg, description_en,
    specifications, sale_price_tyiyn, old_price_tyiyn,
    stock_quantity, reserved_quantity, minimum_stock, warranty_months,
    installment_allowed, manager_commission_type, manager_commission_value,
    is_active, is_featured, status, created_by
  ) values (
    v_category_id, v_brand_id, v_sku, v_slug, v_item.model,
    trim(p_product ->> 'name_ru'),
    coalesce(nullif(trim(p_product ->> 'name_kg'),''), trim(p_product ->> 'name_ru')),
    coalesce(nullif(trim(p_product ->> 'name_en'),''), trim(p_product ->> 'name_ru')),
    nullif(trim(p_product ->> 'description_ru'),''),
    nullif(trim(p_product ->> 'description_kg'),''),
    nullif(trim(p_product ->> 'description_en'),''),
    coalesce(p_product -> 'specifications','[]'::jsonb),
    v_sale_price, v_old_price,
    0, 0, v_minimum_stock, v_warranty,
    coalesce((p_product ->> 'installment_allowed')::boolean,true),
    v_commission_type, v_commission_value,
    coalesce((p_product ->> 'is_active')::boolean,true),
    coalesce((p_product ->> 'is_featured')::boolean,false),
    case when coalesce((p_product ->> 'is_active')::boolean,true) then 'out_of_stock' else 'hidden' end,
    auth.uid()
  ) returning id into v_product_id;

  insert into public.supplier_products (
    supplier_id, product_id, supplier_sku, purchase_price_tyiyn,
    is_primary, is_active, last_purchase_at, delivery_item_id
  ) values (
    v_delivery.supplier_id, v_product_id, v_item.supplier_sku,
    v_item.purchase_price_tyiyn, true, true, v_delivery.delivered_at, v_item.id
  );

  update public.supplier_delivery_items
  set product_id = v_product_id, updated_at = now()
  where id = v_item.id;

  insert into public.inventory_movements (
    product_id, movement_type, quantity_delta, balance_after,
    reference_type, reference_id, supplier_id, note, created_by
  ) values (
    v_product_id, 'purchase', v_item.quantity, 0,
    'supplier_delivery_item', v_item.id, v_delivery.supplier_id,
    'Приход по поставке №' || v_delivery.delivery_number::text,
    auth.uid()
  );

  return jsonb_build_object(
    'product_id', v_product_id,
    'delivery_item_id', v_item.id,
    'supplier_id', v_delivery.supplier_id,
    'stock_quantity', v_item.quantity,
    'purchase_price_tyiyn', v_item.purchase_price_tyiyn
  );
end;
$$;

create or replace function public.delete_product_safely(p_product_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Только управляющий может удалять товары'; end if;
  if not exists (select 1 from public.products where id = p_product_id and deleted_at is null) then
    raise exception 'Товар не найден или уже удалён';
  end if;

  update public.products
  set is_active = false, status = 'archived', deleted_at = now()
  where id = p_product_id;

  update public.supplier_products
  set is_active = false, updated_at = now()
  where product_id = p_product_id;

  insert into public.audit_logs(actor_id, table_name, record_id, action, metadata)
  values (
    auth.uid(), 'products', p_product_id::text, 'RPC',
    jsonb_build_object('function','delete_product_safely','operation','soft_delete')
  );
end;
$$;

create or replace function public.calculate_installment_terms(
  p_amount_tyiyn bigint,
  p_months integer
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_config jsonb;
  v_plan jsonb;
  v_rate integer;
  v_minimum bigint;
  v_overpayment bigint;
  v_total bigint;
begin
  if p_amount_tyiyn <= 0 then raise exception 'Сумма рассрочки должна быть больше нуля'; end if;
  if p_months is null or p_months < 1 or p_months > 12 then raise exception 'Некорректный срок рассрочки'; end if;

  select value into v_config from public.app_settings where key = 'installment_config';
  v_config := coalesce(v_config, '{}'::jsonb);
  v_minimum := coalesce((v_config ->> 'minimum_tyiyn')::bigint,0);
  if p_amount_tyiyn < v_minimum then raise exception 'Сумма меньше минимальной для рассрочки'; end if;

  select value into v_plan
  from jsonb_array_elements(coalesce(v_config -> 'plans','[]'::jsonb))
  where coalesce((value ->> 'enabled')::boolean,false)
    and (value ->> 'months')::integer = p_months
  limit 1;
  if v_plan is null then raise exception 'Выбранный срок рассрочки недоступен'; end if;

  v_rate := coalesce((v_plan ->> 'rate_basis_points')::integer,0);
  v_overpayment := round(p_amount_tyiyn::numeric * v_rate / 10000)::bigint;
  v_total := p_amount_tyiyn + v_overpayment;

  return jsonb_build_object(
    'months', p_months,
    'rate_basis_points', v_rate,
    'base_tyiyn', p_amount_tyiyn,
    'overpayment_tyiyn', v_overpayment,
    'total_tyiyn', v_total,
    'monthly_payment_tyiyn', (v_total + p_months - 1) / p_months
  );
end;
$$;

create or replace function public.apply_installment_terms_to_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_base bigint;
  v_terms jsonb;
begin
  if new.requested_purchase_method = 'installment' then
    if new.requested_installment_months is null then raise exception 'Укажите срок рассрочки'; end if;
    v_base := coalesce(
      nullif(new.request_metadata ->> 'installment_base_tyiyn','')::bigint,
      new.subtotal_tyiyn - new.discount_tyiyn + new.delivery_tyiyn
    );
    v_terms := public.calculate_installment_terms(v_base, new.requested_installment_months);
    new.total_tyiyn := (v_terms ->> 'total_tyiyn')::bigint;
    new.request_metadata := coalesce(new.request_metadata,'{}'::jsonb) || jsonb_build_object(
      'installment_rate_applied', true,
      'installment_base_tyiyn', v_base,
      'installment_rate_basis_points', (v_terms ->> 'rate_basis_points')::integer,
      'installment_overpayment_tyiyn', (v_terms ->> 'overpayment_tyiyn')::bigint,
      'installment_monthly_payment_tyiyn', (v_terms ->> 'monthly_payment_tyiyn')::bigint
    );
  elsif coalesce((new.request_metadata ->> 'installment_rate_applied')::boolean,false) then
    v_base := coalesce(
      nullif(new.request_metadata ->> 'installment_base_tyiyn','')::bigint,
      new.subtotal_tyiyn - new.discount_tyiyn + new.delivery_tyiyn
    );
    new.total_tyiyn := v_base;
    new.request_metadata := new.request_metadata
      - 'installment_rate_applied'
      - 'installment_rate_basis_points'
      - 'installment_overpayment_tyiyn'
      - 'installment_monthly_payment_tyiyn';
  end if;
  return new;
end;
$$;

drop trigger if exists orders_apply_installment_terms on public.orders;
create trigger orders_apply_installment_terms
before insert or update of requested_purchase_method, requested_installment_months, subtotal_tyiyn, discount_tyiyn, delivery_tyiyn
on public.orders
for each row execute function public.apply_installment_terms_to_order();

create or replace function public.create_public_order_v2(p_payload jsonb, p_fingerprint text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_result jsonb;
  v_order public.orders%rowtype;
begin
  v_result := public.create_public_order(p_payload, p_fingerprint);
  select * into v_order from public.orders where id = (v_result ->> 'order_id')::uuid;
  return v_result || jsonb_build_object(
    'total_tyiyn', v_order.total_tyiyn,
    'subtotal_tyiyn', v_order.subtotal_tyiyn,
    'installment', case
      when v_order.requested_purchase_method = 'installment' then
        jsonb_build_object(
          'months', v_order.requested_installment_months,
          'rate_basis_points', (v_order.request_metadata ->> 'installment_rate_basis_points')::integer,
          'overpayment_tyiyn', (v_order.request_metadata ->> 'installment_overpayment_tyiyn')::bigint,
          'monthly_payment_tyiyn', (v_order.request_metadata ->> 'installment_monthly_payment_tyiyn')::bigint
        )
      else null
    end
  );
end;
$$;

create or replace function public.create_staff_order_with_payment(
  p_customer jsonb,
  p_items jsonb,
  p_sale_channel text default 'offline',
  p_source text default 'store',
  p_delivery jsonb default '{}'::jsonb,
  p_comment text default null,
  p_assigned_manager_id uuid default null,
  p_purchase_method text default 'full',
  p_installment_months integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
  v_order public.orders%rowtype;
begin
  if p_purchase_method not in ('full','installment') then raise exception 'Некорректный способ покупки'; end if;
  if p_purchase_method = 'installment' and p_installment_months is null then raise exception 'Укажите срок рассрочки'; end if;
  if p_purchase_method = 'full' then p_installment_months := null; end if;

  v_result := public.create_staff_order(
    p_customer,
    p_items,
    p_sale_channel,
    p_source,
    p_delivery,
    p_comment,
    p_assigned_manager_id
  );

  update public.orders
  set requested_purchase_method = p_purchase_method,
      requested_installment_months = p_installment_months
  where id = (v_result ->> 'order_id')::uuid
  returning * into v_order;

  return v_result || jsonb_build_object(
    'total_tyiyn', v_order.total_tyiyn,
    'subtotal_tyiyn', v_order.subtotal_tyiyn,
    'requested_purchase_method', v_order.requested_purchase_method,
    'requested_installment_months', v_order.requested_installment_months
  );
end;
$$;

alter table public.installment_plans
  drop constraint if exists installment_plans_months_check;
alter table public.installment_plans
  add constraint installment_plans_months_check check (months between 1 and 12);

-- Keep the financial function authoritative: it snapshots supplier cost and
-- manager commission once, and creates an exact installment schedule.
create or replace function public.confirm_order_sale(
  p_order_id uuid,
  p_payment_method text default 'cash',
  p_received_tyiyn bigint default 0,
  p_installment_months integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
  v_product public.products%rowtype;
  v_supplier_product record;
  v_cost bigint;
  v_commission bigint;
  v_commission_total bigint := 0;
  v_paid bigint;
  v_remaining bigint;
  v_plan_id uuid;
  v_base_payment bigint;
  v_remainder bigint;
  v_i integer;
begin
  if not public.is_active_staff() then raise exception 'Нет доступа'; end if;
  if p_payment_method not in ('cash','card','transfer','installment','other') then
    raise exception 'Некорректный способ оплаты';
  end if;
  if p_received_tyiyn < 0 then raise exception 'Оплата не может быть отрицательной'; end if;
  if p_installment_months is not null and (p_installment_months < 1 or p_installment_months > 12) then
    raise exception 'Некорректный срок рассрочки';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'Заказ не найден'; end if;
  if not (public.is_admin() or v_order.assigned_manager_id = auth.uid()) then raise exception 'Нет доступа к заказу'; end if;
  if v_order.financial_processed then raise exception 'Продажа уже проведена'; end if;
  if v_order.status in ('rejected','cancelled') then raise exception 'Нельзя провести отменённый заказ'; end if;

  if p_installment_months is not null
     and not coalesce((v_order.request_metadata ->> 'installment_rate_applied')::boolean,false) then
    update public.orders
    set requested_purchase_method = 'installment',
        requested_installment_months = p_installment_months
    where id = p_order_id
    returning * into v_order;
  end if;

  if p_received_tyiyn > v_order.total_tyiyn - v_order.paid_tyiyn then raise exception 'Оплата превышает остаток заказа'; end if;

  if not v_order.inventory_processed then
    for v_item in select * from public.order_items where order_id = p_order_id order by created_at
    loop
      select * into v_product from public.products where id = v_item.product_id for update;
      if not found then raise exception 'Товар из заказа не найден'; end if;
      if v_order.inventory_reserved then
        if v_product.stock_quantity < v_item.quantity or v_product.reserved_quantity < v_item.quantity then
          raise exception 'Недостаточно зарезервированного товара: %', v_product.name_ru;
        end if;
      elsif v_product.stock_quantity - v_product.reserved_quantity < v_item.quantity then
        raise exception 'Недостаточно товара: %', v_product.name_ru;
      end if;
      if v_order.inventory_reserved then
        update public.products set reserved_quantity = reserved_quantity - v_item.quantity where id = v_product.id;
      end if;
      insert into public.inventory_movements (
        product_id, movement_type, quantity_delta, balance_after,
        reference_type, reference_id, note, created_by
      ) values (
        v_product.id, 'sale', -v_item.quantity, 0,
        'order', p_order_id, 'Выдача по заказу №' || v_order.order_number::text, auth.uid()
      );
    end loop;
    update public.orders
    set inventory_processed = true, inventory_reserved = false, inventory_returned = false
    where id = p_order_id;
  end if;

  for v_item in select * from public.order_items where order_id = p_order_id order by created_at
  loop
    select sp.id, sp.supplier_id, sp.purchase_price_tyiyn
    into v_supplier_product
    from public.supplier_products sp
    where sp.product_id = v_item.product_id and sp.is_active = true
    order by sp.is_primary desc, sp.updated_at desc limit 1;
    if not found then raise exception 'Для товара "%" не назначен поставщик и закупочная цена', v_item.product_name; end if;

    select * into v_product from public.products where id = v_item.product_id;
    v_cost := v_supplier_product.purchase_price_tyiyn * v_item.quantity;
    v_commission := case
      when v_product.manager_commission_type = 'percent'
        then round(v_item.line_total_tyiyn * v_product.manager_commission_value / 10000.0)::bigint
      else v_product.manager_commission_value * v_item.quantity
    end;

    insert into public.order_item_financials (
      order_item_id, supplier_id, unit_cost_tyiyn, total_cost_tyiyn, manager_commission_tyiyn
    ) values (
      v_item.id, v_supplier_product.supplier_id,
      v_supplier_product.purchase_price_tyiyn, v_cost, v_commission
    );
    insert into public.supplier_debts(supplier_id, order_id, amount_tyiyn)
    values (v_supplier_product.supplier_id, p_order_id, v_cost)
    on conflict (supplier_id, order_id) do update
      set amount_tyiyn = excluded.amount_tyiyn, updated_at = now();
    v_commission_total := v_commission_total + v_commission;
  end loop;

  if v_order.assigned_manager_id is not null and v_commission_total > 0 then
    insert into public.manager_commissions(manager_id, order_id, amount_tyiyn)
    values (v_order.assigned_manager_id, p_order_id, v_commission_total);
  end if;

  update public.orders set financial_processed = true, payment_method = p_payment_method where id = p_order_id;
  if p_received_tyiyn > 0 then
    insert into public.payments(order_id, amount_tyiyn, payment_method, status, note, created_by)
    values (p_order_id, p_received_tyiyn, p_payment_method, 'completed', 'Оплата подтверждена после завершения заказа', auth.uid());
  end if;

  select paid_tyiyn into v_paid from public.orders where id = p_order_id;
  v_remaining := v_order.total_tyiyn - v_paid;
  if p_installment_months is not null and v_remaining > 0 then
    insert into public.installment_plans(order_id, total_tyiyn, down_payment_tyiyn, months, created_by)
    values (p_order_id, v_order.total_tyiyn, v_paid, p_installment_months, auth.uid())
    returning id into v_plan_id;

    v_base_payment := v_remaining / p_installment_months;
    v_remainder := v_remaining % p_installment_months;
    for v_i in 1..p_installment_months loop
      insert into public.installment_schedule(
        installment_plan_id, installment_number, due_date, amount_tyiyn
      ) values (
        v_plan_id, v_i, (current_date + make_interval(months => v_i))::date,
        v_base_payment + case when v_i <= v_remainder then 1 else 0 end
      );
    end loop;
  end if;

  update public.orders
  set status = case when v_remaining = 0 then 'paid' when p_installment_months is not null then 'installment' else 'confirmed' end,
      payment_status = case when v_remaining = 0 then 'paid' when v_paid > 0 then 'partial' else 'unpaid' end
  where id = p_order_id;

  update public.customers
  set total_orders = total_orders + 1,
      total_spent_tyiyn = total_spent_tyiyn + v_order.total_tyiyn,
      last_purchase_at = now()
  where id = v_order.customer_id;
  if v_order.lead_id is not null then update public.leads set status = 'won' where id = v_order.lead_id; end if;

  insert into public.audit_logs(actor_id, table_name, record_id, action, metadata)
  values (
    auth.uid(), 'orders', p_order_id::text, 'RPC',
    jsonb_build_object('function','confirm_order_sale','commission_tyiyn',v_commission_total,'received_tyiyn',p_received_tyiyn)
  );

  return jsonb_build_object(
    'order_id', p_order_id, 'total_tyiyn', v_order.total_tyiyn,
    'paid_tyiyn', v_paid, 'remaining_tyiyn', v_remaining,
    'manager_commission_tyiyn', v_commission_total,
    'installment_plan_id', v_plan_id
  );
end;
$$;

-- Successful delivery must preserve the requested installment instead of
-- silently converting it to a full payment.
create or replace function public.set_order_status(
  p_order_id uuid,
  p_new_status text,
  p_comment text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_old_status text;
  v_item public.order_items%rowtype;
  v_product public.products%rowtype;
begin
  if not public.is_active_staff() then raise exception 'Нет доступа'; end if;
  if p_new_status not in ('new','in_progress','confirmed','courier_picked_up','courier_in_transit','completed','rejected','cancelled') then
    raise exception 'Некорректный статус';
  end if;
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'Заказ не найден'; end if;
  if not (public.is_admin() or v_order.assigned_manager_id = auth.uid()) then raise exception 'Нет доступа к заказу'; end if;
  if v_order.status in ('completed','rejected','cancelled') and p_new_status <> v_order.status then
    raise exception 'Завершённый заказ нельзя вернуть в работу';
  end if;

  v_old_status := v_order.status;
  if p_new_status <> v_old_status and not (
    (v_old_status = 'new' and p_new_status in ('in_progress','confirmed','rejected','cancelled'))
    or (v_old_status = 'in_progress' and p_new_status in ('confirmed','rejected','cancelled'))
    or (v_old_status in ('confirmed','courier_requested','assembled') and p_new_status in ('courier_picked_up','completed','rejected','cancelled'))
    or (v_old_status in ('courier_picked_up','handed_to_courier') and p_new_status in ('courier_in_transit','completed','rejected','cancelled'))
    or (v_old_status in ('courier_in_transit','received') and p_new_status in ('completed','rejected','cancelled'))
    or (v_old_status in ('paid','installment') and p_new_status = 'completed')
  ) then raise exception 'Недопустимый переход статуса: % → %', v_old_status, p_new_status; end if;

  if p_new_status = v_old_status and not (
    (p_new_status = 'confirmed' and not v_order.inventory_reserved and not v_order.inventory_processed)
    or (p_new_status in ('courier_picked_up','courier_in_transit') and not v_order.inventory_processed)
    or (p_new_status = 'completed' and not v_order.financial_processed)
  ) then return v_order; end if;

  if p_new_status in ('confirmed','courier_picked_up','courier_in_transit','completed')
     and not v_order.inventory_reserved and not v_order.inventory_processed then
    for v_item in select * from public.order_items where order_id = p_order_id order by created_at
    loop
      select * into v_product from public.products where id = v_item.product_id for update;
      if not found then raise exception 'Товар из заказа не найден'; end if;
      if v_product.stock_quantity - v_product.reserved_quantity < v_item.quantity then
        raise exception 'Недостаточно товара: %', v_product.name_ru;
      end if;
      update public.products set reserved_quantity = reserved_quantity + v_item.quantity where id = v_product.id;
    end loop;
    update public.orders set inventory_reserved = true where id = p_order_id;
    v_order.inventory_reserved := true;
  end if;

  if p_new_status in ('courier_picked_up','courier_in_transit','completed') and not v_order.inventory_processed then
    for v_item in select * from public.order_items where order_id = p_order_id order by created_at
    loop
      select * into v_product from public.products where id = v_item.product_id for update;
      if v_product.stock_quantity < v_item.quantity or v_product.reserved_quantity < v_item.quantity then
        raise exception 'Недостаточно зарезервированного товара: %', v_product.name_ru;
      end if;
      update public.products set reserved_quantity = reserved_quantity - v_item.quantity where id = v_product.id;
      insert into public.inventory_movements(
        product_id, movement_type, quantity_delta, balance_after,
        reference_type, reference_id, note, created_by
      ) values (
        v_product.id, 'sale', -v_item.quantity, 0,
        'courier_dispatch', p_order_id,
        'Товар забрал курьер по заказу №' || v_order.order_number::text, auth.uid()
      );
    end loop;
    update public.orders
    set inventory_processed = true, inventory_reserved = false, inventory_returned = false,
        courier_advance_tyiyn = total_tyiyn, courier_advance_status = 'pending'
    where id = p_order_id;
    v_order.inventory_processed := true;
    v_order.inventory_reserved := false;
    v_order.courier_advance_tyiyn := v_order.total_tyiyn;
  end if;

  if p_new_status in ('rejected','cancelled') then
    if v_order.financial_processed then raise exception 'Проведённую продажу отменяйте через раздел возвратов'; end if;
    if v_order.inventory_processed and not v_order.inventory_returned then
      for v_item in select * from public.order_items where order_id = p_order_id order by created_at
      loop
        insert into public.inventory_movements(
          product_id, movement_type, quantity_delta, balance_after,
          reference_type, reference_id, note, created_by
        ) values (
          v_item.product_id, 'return_in', v_item.quantity, 0,
          'courier_refusal', p_order_id,
          'Клиент не принял заказ №' || v_order.order_number::text, auth.uid()
        );
      end loop;
      update public.orders
      set inventory_returned = true,
          courier_advance_status = case when courier_advance_tyiyn > 0 then 'refunded' else 'not_received' end
      where id = p_order_id;
    elsif v_order.inventory_reserved then
      for v_item in select * from public.order_items where order_id = p_order_id order by created_at
      loop
        update public.products
        set reserved_quantity = greatest(0, reserved_quantity - v_item.quantity)
        where id = v_item.product_id;
      end loop;
      update public.orders set inventory_reserved = false, courier_advance_status = 'not_received' where id = p_order_id;
    end if;
  end if;

  if p_new_status = 'completed' and not v_order.financial_processed then
    perform public.confirm_order_sale(
      p_order_id,
      case when v_order.requested_purchase_method = 'installment' then 'installment' else 'other' end,
      case when v_order.requested_purchase_method = 'installment' then 0 else v_order.total_tyiyn end,
      case when v_order.requested_purchase_method = 'installment' then v_order.requested_installment_months else null end
    );
  end if;

  update public.orders
  set status = p_new_status,
      completed_at = case when p_new_status = 'completed' then now() else completed_at end,
      courier_advance_status = case when p_new_status = 'completed' then 'settled' else courier_advance_status end
  where id = p_order_id returning * into v_order;

  if v_order.lead_id is not null then
    update public.leads
    set status = case
      when p_new_status = 'completed' then 'won'
      when p_new_status = 'rejected' then 'lost'
      when p_new_status = 'cancelled' then 'cancelled'
      when p_new_status = 'new' then 'new'
      when p_new_status = 'in_progress' then 'in_progress'
      else 'confirmed'
    end,
    message = coalesce(p_comment, message)
    where id = v_order.lead_id;
  end if;
  if p_comment is not null then
    update public.order_status_history set comment = p_comment
    where id = (
      select id from public.order_status_history
      where order_id = p_order_id and old_status = v_old_status and new_status = p_new_status
      order by created_at desc limit 1
    );
  end if;
  return v_order;
end;
$$;

revoke all on function public.create_supplier_with_delivery(jsonb,jsonb,text) from public;
revoke all on function public.create_supplier_delivery(uuid,jsonb,text,date) from public;
revoke all on function public.create_product_from_delivery_item(uuid,jsonb) from public;
revoke all on function public.delete_product_safely(uuid) from public;
revoke all on function public.calculate_installment_terms(bigint,integer) from public;
revoke all on function public.create_public_order_v2(jsonb,text) from public;
revoke all on function public.create_staff_order_with_payment(jsonb,jsonb,text,text,jsonb,text,uuid,text,integer) from public;
revoke all on function public.apply_installment_terms_to_order() from public;

revoke execute on function public.create_supplier_with_delivery(jsonb,jsonb,text) from anon;
revoke execute on function public.create_supplier_delivery(uuid,jsonb,text,date) from anon;
revoke execute on function public.create_product_from_delivery_item(uuid,jsonb) from anon;
revoke execute on function public.delete_product_safely(uuid) from anon;
revoke execute on function public.create_staff_order_with_payment(jsonb,jsonb,text,text,jsonb,text,uuid,text,integer) from anon;
revoke execute on function public.calculate_installment_terms(bigint,integer) from anon, authenticated;
revoke execute on function public.apply_installment_terms_to_order() from anon, authenticated;
revoke execute on function public.create_public_order_v2(jsonb,text) from anon, authenticated;

grant execute on function public.create_supplier_with_delivery(jsonb,jsonb,text) to authenticated;
grant execute on function public.create_supplier_delivery(uuid,jsonb,text,date) to authenticated;
grant execute on function public.create_product_from_delivery_item(uuid,jsonb) to authenticated;
grant execute on function public.delete_product_safely(uuid) to authenticated;
grant execute on function public.create_public_order_v2(jsonb,text) to service_role;
grant execute on function public.create_staff_order_with_payment(jsonb,jsonb,text,text,jsonb,text,uuid,text,integer) to authenticated;
